set:
  features: false
  train: false
  collect_prototype: false
  eval_train: false
  eval: true
  basic_eval: false
path:
  root_dir:  /share/database/tyz/Development_Set
  train_dir: /share/database/tyz/Development_Set/Training_Set
  eval_dir:  /share/database/tyz/Development_Set/Validation_Set
  feat_path: /share/database/tyz/Development_Feat
  feat_train: ${path.feat_path}/feat_train
  feat_eval:  ${path.feat_path}/feat_eval
  pretrained_model: /share/tyz/data_experiment/DCASE_2022_few_shot/distill_extractor_9_1/best_model.pth
  Model: /share/tyz/data_experiment/DCASE_2022_few_shot/distill_extractor_9_1
  prototype: /share/tyz/data_experiment/DCASE_2022_few_shot/distill_extractor_9_1/prototype.pth
  best_model: ${path.Model}/best_model.pth
  last_model: ${path.Model}/last_model.pth

features:
  seg_len: 0.200
  hop_seg: 0.100
  eps: 2.220446049250313e-16
  fmax: 11025
  fmin: 50
  sr: 22050
  n_fft: 1024
  n_mels: 128
  hop_mel: 256
  
train:
  num_classes: 15
  n_shot: 5
  k_way : 30
  device: cuda
  lr_rate: 0.001
  scheduler_gamma: 0.2
  scheduler_step_size: 15
  epochs: 50
  num_episodes:
  encoder: Resnet  # Protonet or Resnet
eval:
  samples_neg: 8
  t: 2
  lr: 0.0001
  p_k: 0.3
  p_k_step: 0.2
  a: 0.5
  iterations: 20
  query_batch_size: 64
  negative_set_batch_size : 000
  threshold: 0.5
  eval_model: ${path.Model}/${eval.iterations}_${eval.lr}_${eval.t}_${eval.query_batch_size}_${eval.samples_neg}
  init_model: ${path.Model}/init_model



